language: php
php:
 - '7.2'
 - '7.3'
 - '7.4'
before_install:
 - phpenv config-add travis.php.ini
 - phpenv config-rm xdebug.ini
before_script:
 - travis_retry composer self-update
 - travis_retry composer install --no-interaction --prefer-source --dev
script:
 - pecl insttall pcov
 - vendor/bin/phpunit --coverage-clover=clover.xml
after_success:
 - bash <(curl -s https://codecov.io/bash)
